# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Uber App For Rider' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Uber App For Rider
  pod ‘Firebase’
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
	
end
