# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Uber App For Driver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Uber App For Driver
  pod ‘Firebase’
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'

end
